Feature: Creation de tout type d OS Isolation sur monExpert

  ce test cree en boucle les 288 OS type Isolation possible sur mon Expert


  Scenario Outline: Creation de tout type d OS Isolation sur monExpert
    Given Je cree mon OS sur Monexpert "<souhait>","<logement>","<chauffageActuel>","<chauffageLogement>","<typeTravaux>","<surface>","<revenus>","<adresseTravaux>","<CP>","<ville>"
    When Je me connecte à monExpert
    Then Je recupere la reference du dernier OS cree dans monExpert
    Examples:
      | souhait | logement    | chauffageActuel | chauffageLogement | typeTravaux                 | surface | revenus              | adresseTravaux     | CP    | ville      |
      | Isoler  | appartement | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 38 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 39 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | electricite     | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | electricite     | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | electricite     | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | gaz             | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | gaz             | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | gaz             | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | fioul           | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | fioul           | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | fioul           | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | bois            | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | bois            | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | bois            | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | bois            | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | bois            | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | charbon         | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | charbon         | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | charbon         | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | maison      | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE | 36 avenue de paris | 78210 | Versailles |
      | Isoler  | appartement | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | comblesPerdusOuAmenageables | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | murs                        | 110     | PRECAIRE_ENERGETIQUE |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | murs                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | murs                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | sols                        | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | sols                        | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | sols                        | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | PRECAIRE             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | MODESTE              |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | individuel        | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | appartement | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
      | Isoler  | maison      | pompeAChaleur   | collectif         | toitureTerrasse             | 110     | STANDARD             |                    |       |            |
